name: Bitwiser Jekyll theme
markdown: redcarpet
pygments: true
gituser: brijeshb42/bitwiser
paginate: 5
paginate_path: "page:num"
email: brijeshb42@gmail.com
#disqus: bitwiser
ga_id: UA-47902363-1
ga_domain: bitwiser.in
desc: Demo website for Bitwiser Jekyll theme.
keywords: bitwiser, jekyll, theme, templates
twitter: brijeshb42