name: Blog Name
markdown: redcarpet
pygments: true
#gituser: username
paginate: 5
paginate_path: "page:num"
#email: email@domain.com
#disqus: disqusdomain
#ga_id: analyticsID
#ga_domain: analyticsDomain
desc: Put website description for your home page.
keywords: some, keywords, metatags
#twitter: twitterHandle